"""initial

Revision ID: 23c3ae6eb28e
Revises: 
Create Date: 2026-01-15 21:45:08.886798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23c3ae6eb28e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('max_capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_booking_reference'))
        batch_op.create_unique_constraint(None, ['booking_reference'])
        batch_op.drop_constraint(batch_op.f('bookings_adventure_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('bookings_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'adventures', ['adventure_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('transaction_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('result_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('payments_booking_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('payments_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payments_booking_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('payments_adventure_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'adventures', ['adventure_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'bookings', ['booking_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_adventure_id_fkey'), 'adventures', ['adventure_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('payments_booking_id_fkey'), 'bookings', ['booking_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('payments_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('payments_booking_id_key'), ['booking_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('result_code',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('transaction_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bookings_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('bookings_adventure_id_fkey'), 'adventures', ['adventure_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_bookings_booking_reference'), ['booking_reference'], unique=True)

    with op.batch_alter_table('adventures', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('max_capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
